export enum Font {
    NunitoSansRegular = "NunitoSans-Regular",
    NunitoSansBold = "NunitoSans-Bold",
    NunitoSansBlack = "NunitoSans-Black",
}

export enum Typography {
    text5Xs = "text-5xs",
    text5XsB = "text-5xs-b",
    text4Xs = "text-4xs",
    text4XsB = "text-4xs-b",
    text3Xs = "text-3xs",
    text3XsB = "text-3xs-b",
    text2Xs = "text-2xs",
    text2XsB = "text-2xs-b",
    textXs = "text-xs",
    textXsB = "text-xs-b",
    textSm = "text-sm",
    textSmB = "text-sm-b",
    textBase = "text-base",
    textBaseB = "text-base-b",
    textLg = "text-lg",
    textLgB = "text-lg-b",
    textXl = "text-xl",
    textXlB = "text-xl-b",
    text2Xl = "text-2xl",
    text2XlB = "text-2xl-b",
    text3Xl = "text-3xl",
    text3XlB = "text-3xl-b",
    text4Xl = "text-4xl",
    text4Point5Xl = "text-4.5xl",
    text4Point5XlB = "text-4.5xl-b",
    text4Point5XlBlack = "text-4.5xl-black",
    text5Xl = "text-5xl",
    text5XlB = "text-5xl-b",
    text6Xl = "text-6xl",
    text7Xl = "text-7xl",
    text8Xl = "text-8xl",
    text9Xl = "text-9xl",
}